allowBuilds:
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@navikt/aksel-icons@8.15.0'
  - '@navikt/ds-css@8.15.0'
  - '@navikt/ds-react@8.15.0'
  - '@navikt/ds-tokens@8.15.0'
  - '@navikt/ds-tailwind@8.15.0'
