apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: reops-sporingsskript-testsider
  namespace: team-researchops
  labels:
    team: team-researchops
spec:
  image: {{image}}
  port: 3000
  env:
    - name: WEBSITE_ID
      value: "8c9ebc0a-63d8-46b2-a34c-9378f809e595"
  ingresses:
    - https://sporingsskript-test.ansatt.nav.no
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  liveness:
    path: /
    initialDelay: 10
  readiness:
    path: /
    initialDelay: 10
